### ISSUE TITLE
Problem Statement Reviews and Comments

### ISSUE THREAD

**Issue by zehongwong** [zehongwong/CAS741_Proj#1]
Hi Dr. @smiths, I just pushed the Problem Statement, could you please take a look on that?

**Comment by smiths** [comment]
Your problem statement is approved @zehongwong.  I'll update your status in the Repos.csv to reflect the approved status and close this issue, once you add me as a collaborator on this project.

Once I've been added as a collaborator, you can assign future issues like this to me.

In the future, it will be nice if you include a link (url) to point me to the artifact that I'm to review.  :smile:

**Comment by zehongwong** [comment]
Great. Thanks Dr. @smiths. Happy Chinese New Year of Rabbit!

**Comment by smiths** [comment]
Thank you @zehongwong.  Happy Chinese New Year to you too!
